name: gwak
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - gwpy=3.0.5
  # omicron dependencies
  - python-ligo-lw=1.8.3
  - pyomicron=2.0.4
  - omicron>=4.0.0
  - dqsegdb2=1.1.3
  # injection dependencies
  # - bilby=1.1.5
  - lal=7.3.1
  - lalsuite=7.15
  # - gsl=2.7
  - pip:
    - torch==2.3.1
    - h5py==3.8.0
    - snakemake==8.14.0
    - matplotlib==3.7.1
    - numpy==1.26.4
    - lightning==2.3.2
    - setGPU
    - jsonargparse==4.29
    - wandb==0.17.3
    - scipy==1.14.1
    - einops==0.8.0
    - nflows==0.14
    - uproot==5.6.0
    - scikit-learn==1.6.1
    - docstring-parser==0.16 
    - importlib-resources==6.5.2 
    - typeshed-client==2.7.0