# lightning.pytorch==2.3.2
seed_everything: 0
trainer:
  callbacks:
    - class_path: callback.ValidationCallback
  accelerator: gpu
  devices: [1]
  # accelerator: auto
  # devices: auto
  strategy: ddp_find_unused_parameters_true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  max_epochs: 50
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
ckpt_path: null
model:
  class_path: models.Linear
  init_args:
    backgrounds: /home/hongyin.chen/whiten_timeslide.h5
    ckpt: /home/katya.govorkova/gwak2/gwak/output/test_S4_fixedSignals_0p5sec_v2/lightning_logs/2wla29uz/checkpoints/33-1700.ckpt
    cfg_path: /home/katya.govorkova/gwak2/gwak/output/test_S4_fixedSignals_0p5sec_v2/config.yaml
    n_dims: 8
data:
  class_path: dataloader.SignalDataloader
  init_args:
    signal_classes:
      - "SineGaussian"
      - "BBH"
      - "Gaussian"
      - "Cusp"
      - "Kink"
      - "KinkKink"
      - "WhiteNoiseBurst"
    priors:
      - class_path: gwak.data.prior.SineGaussianBBC
      - class_path: gwak.data.prior.LAL_BBHPrior
      - class_path: gwak.data.prior.GaussianBBC
      - class_path: gwak.data.prior.CuspBBC
      - class_path: gwak.data.prior.KinkBBC
      - class_path: gwak.data.prior.KinkkinkBBC
      - class_path: gwak.data.prior.WhiteNoiseBurstBBC
    waveforms:
      - class_path: ml4gw.waveforms.SineGaussian
        init_args:
          sample_rate: 0
          duration: 0
      - class_path: ml4gw.waveforms.IMRPhenomPv2
        init_args: {}
      - class_path: ml4gw.waveforms.Gaussian
        init_args:
          sample_rate: 0
          duration: 0
      - class_path: ml4gw.waveforms.GenerateString
        init_args:
          sample_rate: 0
      - class_path: ml4gw.waveforms.GenerateString
        init_args:
          sample_rate: 0
      - class_path: ml4gw.waveforms.GenerateString
        init_args:
          sample_rate: 0
      - class_path: ml4gw.waveforms.WhiteNoiseBurst
        init_args:
          sample_rate: 0
          duration: 0
    extra_kwargs:
      - null
      - ringdown_duration: 0.9
      - null
      - null
      - null
      - null
      - null
    data_dir: /home/katya.govorkova/gwak2_background
    sample_rate: 2048
    kernel_length: 0.5
    psd_length: 64
    fduration: 1
    fftlength: 2
    batch_size: 128
    batches_per_epoch: 10
    num_workers: 2
    data_saving_file: null