# lightning.pytorch==2.3.2
seed_everything: 0
trainer:
  callbacks:
    - class_path: callback.ValidationCallback
  accelerator: gpu
  devices: [0]
  # accelerator: auto
  # devices: auto
  strategy: ddp_find_unused_parameters_true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  log_every_n_steps: 10
  max_epochs: 10
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
ckpt_path: null
model:
  class_path: models.Crayon
  init_args:
    num_ifos: 2
    num_timesteps: 200
    d_output: 8
    d_contrastive_space: 8
    temperature: 0.1
    supervised_simclr: true
data:
  class_path: dataloader.SignalDataloader
  init_args:
    signal_classes:
      - "SineGaussian"
      - "BBH"
    priors:
      - class_path: gwak.data.prior.SineGaussianBBC
      - class_path: gwak.data.prior.LAL_BBHPrior
    waveforms:
      - class_path: ml4gw.waveforms.SineGaussian
        init_args:
          sample_rate: 0
          duration: 0
      - class_path: ml4gw.waveforms.IMRPhenomPv2
        init_args: {}
    extra_kwargs:
      - null
      - ringdown_duration: 0.9
    data_dir: /n/holystore01/LABS/iaifi_lab/Lab/sambt/LIGO/gwak2_background
    sample_rate: 2048
    kernel_length: 0.09765625
    psd_length: 64
    fduration: 1
    fftlength: 2
    batch_size: 128
    batches_per_epoch: 10
    num_workers: 1
    data_saving_file: output/mixed_SG_BBH.h5