project: combination
model_dir: null # If null >> Automatic resolve to gwak/gwak/output
output_dir: null # If null >> Automatic resolve to gwak/gwak/output/export
clean: True
background_batch_size: 2
stride_batch_size: 256
num_ifos: 2
gwak_instances: 8
platform: TORCHSCRIPT
# platform: ONNX
psd_length: 64
kernel_length: 0.5
fduration: 1
fftlength: 2
sample_rate: 4096
preproc_instances: 1
inference_sampling_rate: 2