ifos: ["H1", "L1"]
psd_length: 64
Tb: 10
# Tb: 86400
# Tb: 2592000
# Tb: 31536000
stride_batch_size: 256
sample_rate: 4096
# fname: /home/hongyin.chen/Data/GWAK_data/gwak_infer_data_4K
fname: /home/katya.govorkova/gwak2/gwak/output/O4_MDC_background/test
# fname: /home/katya.govorkova/gwak2_background
ccsn_repo: /home/hongyin.chen/Data/3DCCSN_PREMIERE/Resampled # 1 kpc
data_format: h5 # gwf
shifts: [0, 1]
project: white_noise_purst
image: hermes/tritonserver:23.01
model_repo_dir: null    # Automatic resolve to gwak/gwak/output/export...
result_dir: null    # Automatic resolve to gwak/gwak/output/infer...
job_rate_limit: 8    # Very limited to the process to allowed for the user at one node ($ulimit -u)
monitor_patients: 1
inference_sampling_rate: 2
inj_type: null